import json
from datetime import datetime
import os

# Ensure output directory exists
os.makedirs("public/data", exist_ok=True)

data = {
    "system": "Stage Monitor",
    "environment": "production",
    "last_updated": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
    "market_state": "neutral",
    "notes": "Generated by stage_monitor_export.py"
}

with open("public/data/status.json", "w") as f:
    json.dump(data, f, indent=2)

print("status.json generated successfully.")
